apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  selector:
    matchLabels:
      app: vote
  replicas: 3
  template:
    metadata:
      name: vote
      labels:
        app: vote
    spec:
      containers:
        - image: europe-west9-docker.pkg.dev/ue-nuage/voting-images/vote
          name: vote