version: '1'
services:

  seed:
    image: europe-west9-docker.pkg.dev/ue-nuage/voting-images/seed
    build: ./seed-data
    depends_on:
      - vote
    networks:
      - front-tier

  vote:
    image: europe-west9-docker.pkg.dev/ue-nuage/voting-images/vote
    build: ./vote
    depends_on:
      - redis
    ports:
      - "5000:5000"
    networks:
      - back-tier
      - front-tier


  redis:
    image: "redis:latest"
    volumes:
      - ./healthchecks:/healthchecks
    depends_on:
      - worker
    networks:
      - back-tier
    healthcheck:
      test: [ "CMD","/healthchecks/redis.sh" ]

  worker:
    image: europe-west9-docker.pkg.dev/ue-nuage/voting-images/worker
    build: ./worker
    depends_on:
      - db
    networks:
      - back-tier

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./healthchecks:/healthchecks
    networks:
      - back-tier
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "apt-get update && apt-get install -y curl && /healthchecks/postgres.sh"]

  result:
    image: europe-west9-docker.pkg.dev/ue-nuage/voting-images/result
    build: ./result
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - back-tier
      - front-tier

networks:
  front-tier:
  back-tier:

volumes:
  db-data: